import { ReactComponent as Telegram } from "./telegram.svg";
import { ReactComponent as Search } from "./search.svg";
import { ReactComponent as Remove } from "./remove.svg";
import { ReactComponent as Settings } from "./settings.svg";
import { ReactComponent as Contacts } from "./contacts.svg";
import { ReactComponent as Back } from "./back.svg";
import { ReactComponent as Logout } from "./logout.svg";
import { ReactComponent as Mail } from "./mail.svg";
import { ReactComponent as Username } from "./username.svg";
import { ReactComponent as Edit } from "./edit.svg";
import { ReactComponent as EyeClose } from "./eyeClose.svg";
import { ReactComponent as Eye } from "./eye.svg";
import { ReactComponent as Supheed } from "./supheed.svg";
import { ReactComponent as Loading } from "./loading.svg";
import { ReactComponent as RemoveUser } from "./removeUser.svg";
import { ReactComponent as Smile } from "./smile.svg";
import { ReactComponent as Reply } from "./reply.svg";
import { ReactComponent as Copy } from "./copy.svg";
import { ReactComponent as Delete } from "./delete.svg";
import { ReactComponent as Dove } from "./dove.svg";
import { ReactComponent as Send } from "./send.svg";
import { ReactComponent as Moon } from "./moon.svg";
import { ReactComponent as Meteor } from "./meteor.svg";
import { ReactComponent as Info } from "./information.svg";
import { ReactComponent as AddUser } from "./addUser.svg";
import { ReactComponent as Animal } from "./animal.svg";
import { ReactComponent as Tail } from "./tail.svg";
import { ReactComponent as Photo } from "./photo.svg";
import { ReactComponent as BackPhoto } from "./backPhoto.svg";
import { ReactComponent as UpPhoto } from "./upPhoto.svg";

export const TelegramIcon = Telegram;
export const SearchIcon = Search;
export const RemoveIcon = Remove;
export const SettingsIcon = Settings;
export const ContactsIcon = Contacts;
export const BackIcon = Back;
export const LogoutIcon = Logout;
export const MailIcon = Mail;
export const UsernameIcon = Username;
export const EditIcon = Edit;
export const EyeCloseIcon = EyeClose;
export const EyeIcon = Eye;
export const SupheedIcon = Supheed;
export const LoadingIcon = Loading;
export const RemoveUserIcon = RemoveUser;
export const SmileIcon = Smile;
export const ReplyIcon = Reply;
export const CopyIcon = Copy;
export const DeleteIcon = Delete;
export const DoveIcon = Dove;
export const SendIcon = Send;
export const MoonIcon = Moon;
export const MeteorIcon = Meteor;
export const InfoIcon = Info;
export const AddUserIcon = AddUser;
export const AnimalIcon = Animal;
export const TailIcon = Tail;
export const PhotoIcon = Photo;
export const BackPhotoIcon = BackPhoto;
export const UpPhotoIcon = UpPhoto;
